from django.db import models

class dados(models.Model):
    NU_ANO_CENSO = models.IntegerField(null=True, blank=True, verbose_name='NU_ANO_CENSO')
    NO_REGIAO = models.CharField(max_length=20, null=True, blank=True, verbose_name='NO_REGIAO')
    CO_REGIAO = models.IntegerField(null=True, blank=True, verbose_name='CO_REGIAO')
    NO_UF = models.CharField(max_length=50, null=True, blank=True, verbose_name='NO_UF')
    SG_UF = models.CharField(max_length=2, null=True, blank=True, verbose_name='SG_UF')
    CO_UF = models.IntegerField(null=True, blank=True, verbose_name='CO_UF')
    NO_MUNICIPIO = models.CharField(max_length=150, null=True, blank=True, verbose_name='NO_MUNICIPIO')
    CO_MUNICIPIO = models.IntegerField(null=True, blank=True, verbose_name='CO_MUNICIPIO')
    IN_CAPITAL = models.IntegerField(null=True, blank=True, verbose_name='IN_CAPITAL')
    TP_DIMENSAO = models.IntegerField(null=True, blank=True, verbose_name='TP_DIMENSAO')
    TP_ORGANIZACAO_ACADEMICA = models.IntegerField(null=True, blank=True, verbose_name='TP_ORGANIZACAO_ACADEMICA')
    TP_REDE = models.IntegerField(null=True, blank=True, verbose_name='TP_REDE')
    TP_CATEGORIA_ADMINISTRATIVA = models.IntegerField(null=True, blank=True, verbose_name='TP_CATEGORIA_ADMINISTRATIVA')
    CO_IES = models.IntegerField(null=True, blank=True, verbose_name='CO_IES')
    NO_CURSO = models.CharField(max_length=200, null=True, blank=True, verbose_name='NO_CURSO')
    CO_CURSO = models.IntegerField(null=True, blank=True, verbose_name='CO_CURSO')
    NO_CINE_ROTULO = models.CharField(max_length=120, null=True, blank=True, verbose_name='NO_CINE_ROTULO')
    CO_CINE_ROTULO = models.CharField(max_length=7, null=True, blank=True, verbose_name='CO_CINE_ROTULO')
    CO_CINE_AREA_GERAL = models.CharField(max_length=2, null=True, blank=True, verbose_name='CO_CINE_AREA_GERAL')
    NO_CINE_AREA_GERAL = models.CharField(max_length=120, null=True, blank=True, verbose_name='NO_CINE_AREA_GERAL')
    CO_CINE_AREA_ESPECIFICA = models.CharField(max_length=3, null=True, blank=True, verbose_name='CO_CINE_AREA_ESPECIFICA')
    NO_CINE_AREA_ESPECIFICA = models.CharField(max_length=120, null=True, blank=True, verbose_name='NO_CINE_AREA_ESPECIFICA')
    CO_CINE_AREA_DETALHADA = models.CharField(max_length=4, null=True, blank=True, verbose_name='CO_CINE_AREA_DETALHADA')
    NO_CINE_AREA_DETALHADA = models.CharField(max_length=120, null=True, blank=True, verbose_name='NO_CINE_AREA_DETALHADA')
    TP_GRAU_ACADEMICO = models.IntegerField(null=True, blank=True, verbose_name='TP_GRAU_ACADEMICO')
    IN_GRATUITO = models.IntegerField(null=True, blank=True, verbose_name='IN_GRATUITO')
    TP_MODALIDADE_ENSINO = models.IntegerField(null=True, blank=True, verbose_name='TP_MODALIDADE_ENSINO')
    TP_NIVEL_ACADEMICO = models.IntegerField(null=True, blank=True, verbose_name='TP_NIVEL_ACADEMICO')
    QT_CURSO = models.IntegerField(null=True, blank=True, verbose_name='QT_CURSO')
    QT_VG_TOTAL = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_TOTAL')
    QT_VG_TOTAL_DIURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_TOTAL_DIURNO')
    QT_VG_TOTAL_NOTURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_TOTAL_NOTURNO')
    QT_VG_TOTAL_EAD = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_TOTAL_EAD')
    QT_VG_NOVA = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_NOVA')
    QT_VG_PROC_SELETIVO = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_PROC_SELETIVO')
    QT_VG_REMANESC = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_REMANESC')
    QT_VG_PROG_ESPECIAL = models.IntegerField(null=True, blank=True, verbose_name='QT_VG_PROG_ESPECIAL')
    QT_INSCRITO_TOTAL = models.IntegerField(null=True, blank=True, verbose_name='QT_INSCRITO_TOTAL')
    QT_INSCRITO_TOTAL_DIURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_INSCRITO_TOTAL_DIURNO')
    QT_INSCRITO_TOTAL_NOTURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_INSCRITO_TOTAL_NOTURNO')
    QT_INSCRITO_TOTAL_EAD = models.IntegerField(null=True, blank=True, verbose_name='QT_INSCRITO_TOTAL_EAD')
    QT_INSC_VG_NOVA = models.IntegerField(null=True, blank=True, verbose_name='QT_INSC_VG_NOVA')
    QT_INSC_PROC_SELETIVO = models.IntegerField(null=True, blank=True, verbose_name='QT_INSC_PROC_SELETIVO')
    QT_INSC_VG_REMANESC = models.IntegerField(null=True, blank=True, verbose_name='QT_INSC_VG_REMANESC')
    QT_INSC_VG_PROG_ESPECIAL = models.IntegerField(null=True, blank=True, verbose_name='QT_INSC_VG_PROG_ESPECIAL')
    QT_ING = models.IntegerField(null=True, blank=True, verbose_name='QT_ING')
    QT_ING_FEM = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_FEM')
    QT_ING_MASC = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_MASC')
    QT_ING_DIURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_DIURNO')
    QT_ING_NOTURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_NOTURNO')
    QT_ING_VG_NOVA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_VG_NOVA')
    QT_ING_VESTIBULAR = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_VESTIBULAR')
    QT_ING_ENEM = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_ENEM')
    QT_ING_AVALIACAO_SERIADA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_AVALIACAO_SERIADA')
    QT_ING_SELECAO_SIMPLIFICA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_SELECAO_SIMPLIFICA')
    QT_ING_EGR = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_EGR')
    QT_ING_OUTRO_TIPO_SELECAO = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_OUTRO_TIPO_SELECAO')
    QT_ING_PROC_SELETIVO = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PROC_SELETIVO')
    QT_ING_VG_REMANESC = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_VG_REMANESC')
    QT_ING_VG_PROG_ESPECIAL = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_VG_PROG_ESPECIAL')
    QT_ING_OUTRA_FORMA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_OUTRA_FORMA')
    QT_ING_0_17 = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_0_17')
    QT_ING_18_24 = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_18_24')
    QT_ING_25_29 = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_25_29')
    QT_ING_30_34 = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_30_34')
    QT_ING_35_39 = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_35_39')
    QT_ING_40_49 = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_40_49')
    QT_ING_50_59 = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_50_59')
    QT_ING_60_MAIS = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_60_MAIS')
    QT_ING_BRANCA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_BRANCA')
    QT_ING_PRETA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PRETA')
    QT_ING_PARDA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PARDA')
    QT_ING_AMARELA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_AMARELA')
    QT_ING_INDIGENA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_INDIGENA')
    QT_ING_CORND = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_CORND')
    QT_MAT = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT')
    QT_MAT_FEM = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_FEM')
    QT_MAT_MASC = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_MASC')
    QT_MAT_DIURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_DIURNO')
    QT_MAT_NOTURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_NOTURNO')
    QT_MAT_0_17 = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_0_17')
    QT_MAT_18_24 = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_18_24')
    QT_MAT_25_29 = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_25_29')
    QT_MAT_30_34 = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_30_34')
    QT_MAT_35_39 = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_35_39')
    QT_MAT_40_49 = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_40_49')
    QT_MAT_50_59 = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_50_59')
    QT_MAT_60_MAIS = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_60_MAIS')
    QT_MAT_BRANCA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_BRANCA')
    QT_MAT_PRETA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PRETA')
    QT_MAT_PARDA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PARDA')
    QT_MAT_AMARELA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_AMARELA')
    QT_MAT_INDIGENA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_INDIGENA')
    QT_MAT_CORND = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_CORND')
    QT_CONC = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC')
    QT_CONC_FEM = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_FEM')
    QT_CONC_MASC = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_MASC')
    QT_CONC_DIURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_DIURNO')
    QT_CONC_NOTURNO = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_NOTURNO')
    QT_CONC_0_17 = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_0_17')
    QT_CONC_18_24 = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_18_24')
    QT_CONC_25_29 = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_25_29')
    QT_CONC_30_34 = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_30_34')
    QT_CONC_35_39 = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_35_39')
    QT_CONC_40_49 = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_40_49')
    QT_CONC_50_59 = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_50_59')
    QT_CONC_60_MAIS = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_60_MAIS')
    QT_CONC_BRANCA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_BRANCA')
    QT_CONC_PRETA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PRETA')
    QT_CONC_PARDA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PARDA')
    QT_CONC_AMARELA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_AMARELA')
    QT_CONC_INDIGENA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_INDIGENA')
    QT_CONC_CORND = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_CORND')
    QT_ING_NACBRAS = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_NACBRAS')
    QT_ING_NACESTRANG = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_NACESTRANG')
    QT_MAT_NACBRAS = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_NACBRAS')
    QT_MAT_NACESTRANG = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_NACESTRANG')
    QT_CONC_NACBRAS = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_NACBRAS')
    QT_CONC_NACESTRANG = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_NACESTRANG')
    QT_ALUNO_DEFICIENTE = models.IntegerField(null=True, blank=True, verbose_name='QT_ALUNO_DEFICIENTE')
    QT_ING_DEFICIENTE = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_DEFICIENTE')
    QT_MAT_DEFICIENTE = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_DEFICIENTE')
    QT_CONC_DEFICIENTE = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_DEFICIENTE')
    QT_ING_FINANC = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_FINANC')
    QT_ING_FINANC_REEMB = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_FINANC_REEMB')
    QT_ING_FIES = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_FIES')
    QT_ING_RPFIES = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_RPFIES')
    QT_ING_FINANC_REEMB_OUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_FINANC_REEMB_OUTROS')
    QT_ING_FINANC_NREEMB = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_FINANC_NREEMB')
    QT_ING_PROUNII = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PROUNII')
    QT_ING_PROUNIP = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PROUNIP')
    QT_ING_NRPFIES = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_NRPFIES')
    QT_ING_FINANC_NREEMB_OUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_FINANC_NREEMB_OUTROS')
    QT_MAT_FINANC = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_FINANC')
    QT_MAT_FINANC_REEMB = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_FINANC_REEMB')
    QT_MAT_FIES = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_FIES')
    QT_MAT_RPFIES = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_RPFIES')
    QT_MAT_FINANC_REEMB_OUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_FINANC_REEMB_OUTROS')
    QT_MAT_FINANC_NREEMB = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_FINANC_NREEMB')
    QT_MAT_PROUNII = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PROUNII')
    QT_MAT_PROUNIP = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PROUNIP')
    QT_MAT_NRPFIES = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_NRPFIES')
    QT_MAT_FINANC_NREEMB_OUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_FINANC_NREEMB_OUTROS')
    QT_CONC_FINANC = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_FINANC')
    QT_CONC_FINANC_REEMB = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_FINANC_REEMB')
    QT_CONC_FIES = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_FIES')
    QT_CONC_RPFIES = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_RPFIES')
    QT_CONC_FINANC_REEMB_OUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_FINANC_REEMB_OUTROS')
    QT_CONC_FINANC_NREEMB = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_FINANC_NREEMB')
    QT_CONC_PROUNII = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PROUNII')
    QT_CONC_PROUNIP = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PROUNIP')
    QT_CONC_NRPFIES = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_NRPFIES')
    QT_CONC_FINANC_NREEMB_OUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_FINANC_NREEMB_OUTROS')
    QT_ING_RESERVA_VAGA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_RESERVA_VAGA')
    QT_ING_RVREDEPUBLICA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_RVREDEPUBLICA')
    QT_ING_RVETNICO = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_RVETNICO')
    QT_ING_RVPDEF = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_RVPDEF')
    QT_ING_RVSOCIAL_RF = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_RVSOCIAL_RF')
    QT_ING_RVOUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_RVOUTROS')
    QT_MAT_RESERVA_VAGA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_RESERVA_VAGA')
    QT_MAT_RVREDEPUBLICA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_RVREDEPUBLICA')
    QT_MAT_RVETNICO = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_RVETNICO')
    QT_MAT_RVPDEF = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_RVPDEF')
    QT_MAT_RVSOCIAL_RF = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_RVSOCIAL_RF')
    QT_MAT_RVOUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_RVOUTROS')
    QT_CONC_RESERVA_VAGA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_RESERVA_VAGA')
    QT_CONC_RVREDEPUBLICA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_RVREDEPUBLICA')
    QT_CONC_RVETNICO = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_RVETNICO')
    QT_CONC_RVPDEF = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_RVPDEF')
    QT_CONC_RVSOCIAL_RF = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_RVSOCIAL_RF')
    QT_CONC_RVOUTROS = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_RVOUTROS')
    QT_SIT_TRANCADA = models.IntegerField(null=True, blank=True, verbose_name='QT_SIT_TRANCADA')
    QT_SIT_DESVINCULADO = models.IntegerField(null=True, blank=True, verbose_name='QT_SIT_DESVINCULADO')
    QT_SIT_TRANSFERIDO = models.IntegerField(null=True, blank=True, verbose_name='QT_SIT_TRANSFERIDO')
    QT_SIT_FALECIDO = models.IntegerField(null=True, blank=True, verbose_name='QT_SIT_FALECIDO')
    QT_ING_PROCESCPUBLICA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PROCESCPUBLICA')
    QT_ING_PROCESCPRIVADA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PROCESCPRIVADA')
    QT_ING_PROCNAOINFORMADA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PROCNAOINFORMADA')
    QT_MAT_PROCESCPUBLICA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PROCESCPUBLICA')
    QT_MAT_PROCESCPRIVADA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PROCESCPRIVADA')
    QT_MAT_PROCNAOINFORMADA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PROCNAOINFORMADA')
    QT_CONC_PROCESCPUBLICA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PROCESCPUBLICA')
    QT_CONC_PROCESCPRIVADA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PROCESCPRIVADA')
    QT_CONC_PROCNAOINFORMADA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PROCNAOINFORMADA')
    QT_PARFOR = models.IntegerField(null=True, blank=True, verbose_name='QT_PARFOR')
    QT_ING_PARFOR = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_PARFOR')
    QT_MAT_PARFOR = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_PARFOR')
    QT_CONC_PARFOR = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_PARFOR')
    QT_APOIO_SOCIAL = models.IntegerField(null=True, blank=True, verbose_name='QT_APOIO_SOCIAL')
    QT_ING_APOIO_SOCIAL = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_APOIO_SOCIAL')
    QT_MAT_APOIO_SOCIAL = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_APOIO_SOCIAL')
    QT_CONC_APOIO_SOCIAL = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_APOIO_SOCIAL')
    QT_ATIV_EXTRACURRICULAR = models.IntegerField(null=True, blank=True, verbose_name='QT_ATIV_EXTRACURRICULAR')
    QT_ING_ATIV_EXTRACURRICULAR = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_ATIV_EXTRACURRICULAR')
    QT_MAT_ATIV_EXTRACURRICULAR = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_ATIV_EXTRACURRICULAR')
    QT_CONC_ATIV_EXTRACURRICULAR = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_ATIV_EXTRACURRICULAR')
    QT_MOB_ACADEMICA = models.IntegerField(null=True, blank=True, verbose_name='QT_MOB_ACADEMICA')
    QT_ING_MOB_ACADEMICA = models.IntegerField(null=True, blank=True, verbose_name='QT_ING_MOB_ACADEMICA')
    QT_MAT_MOB_ACADEMICA = models.IntegerField(null=True, blank=True, verbose_name='QT_MAT_MOB_ACADEMICA')
    QT_CONC_MOB_ACADEMICA = models.IntegerField(null=True, blank=True, verbose_name='QT_CONC_MOB_ACADEMICA')

    def __str__(self):
        return self.NO_CURSO
    
    class Meta:
        ordering = ['id']